services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: citylunch
      POSTGRES_USER: citylunch
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8026:8025"   # UI web (8026 côté hôte)

volumes:
  pg_data:
